site_name: Solus Help Center
site_url: https://170.187.159.75
site_description: Documentation for the Solus Project, an independent Linux-based operating system.
site_author: Solus Project
copyright: (C) 2015-2022 Solus Project
